name: Build Aseprite

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Aseprite Version'
        required: true
        default: 'v1.3.13'
        type: string

jobs:
  build:
    name: Build Aseprite (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build g++ clang libc++-dev libc++abi-dev libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev curl git jq
          sudo ln -sf /usr/bin/clang++ /usr/bin/c++

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake ninja llvm fontconfig curl git jq
          brew link --overwrite cmake

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y cmake ninja git curl jq

      - name: Get Latest Skia URL (Linux)
        if: runner.os == 'Linux'
        run: |
          SKIA_URL=$(curl -s https://api.github.com/repos/aseprite/skia/releases/latest | \
                     jq -r '.assets[] | select(.name | contains("Skia-Linux-Release-x64-libc++")) | .browser_download_url')
          if [ -z "$SKIA_URL" ] || [ "$SKIA_URL" = "null" ]; then echo "Error: Skia URL not found!"; exit 1; fi
          curl -L -o skia.zip "$SKIA_URL"
          unzip skia.zip -d skia
          if [ ! -f "skia/libskia.a" ]; then echo "Error: libskia.a not found!"; exit 1; fi

      - name: Clone Aseprite (with submodules)
        run: |
          git clone --recursive --depth=1 --branch ${{ github.event.inputs.version || 'v1.3.13' }} https://github.com/aseprite/aseprite.git aseprite
          if [ ! -f "aseprite/CMakeLists.txt" ]; then echo "Error: CMakeLists.txt not found!"; exit 1; fi

      - name: Build Aseprite
        run: |
          cd aseprite
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release \
                -DLAF_BACKEND=skia \
                -DSKIA_DIR=../../skia \
                -DSKIA_LIBRARY_DIR=../../skia \
                -DSKIA_LIBRARY=../../skia/libskia.a ..
          ninja

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ matrix.os }}
          path: aseprite/build/bin/aseprite*

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: aseprite/build/bin/aseprite*
          tag_name: aseprite-${{ github.event.inputs.version }}
          name: "Aseprite ${{ github.event.inputs.version }} Release"
          body: "Compiled version of Aseprite ${{ github.event.inputs.version }} for Windows, Linux, and macOS"
